ALTER PACKAGE package_name COMPILE SPECIFICATION PLSQL_CODE_TYPE=NATIVE;

ALTER SESSION SET PLSQL_OPTIMIZE_LEVEL=2;

ALTER PACKAGE package_name COMPILE DEBUG SPECIFICATION;

SELECT  PLSQL_WARNINGS,
        PLSQL_OPTIMIZE_LEVEL,
        PLSQL_CODE_TYPE
  FROM
SYS.ALL_PLSQL_OBJECT_SETTINGS
WHERE NAME= 'package_name';