--testing
select * from DBA_SYS_PRIVS  where grantee like 'XXLINK%';
select * from DBA_SYS_PRIVS  where grantee like 'XXSADEL%';
select * from USER_SYS_PRIVS;



sELECT COLUMN_NAME FROM GT_COLUMNS_NAMES order by COLUMN_NAME asc;
  
  
  DELETE FROM GT_TABLE_NAMES;
  
select count(*) from GT_TABLE_NAMES;
select count(*) from GT_COLUMNS_NAMES;

SELECT count(*) FROM user_tables;
SELECT  count(*) FROM ALL_TAB_COLUMNS WHERE OWNER = 'XXLINK';

SELECT * FROM GT_TABLE_NAMES WHERE TBL_NAME_ID = 25;

SELECT * FROM ALL_TAB_COLUMNS  WHERE OWNER = 'XXLINK';

SELECT * FROM USER_CONS_COLUMNS;


(SELECT COLUMN_NAME FROM GT_COLUMNS_NAMES ) 
MINUS
(SELECT COLUMN_NAME FROM ALL_TAB_COLUMNS WHERE OWNER = 'XXLINK' );

(SELECT COLUMN_NAME FROM ALL_TAB_COLUMNS WHERE OWNER = 'XXLINK' )
MINUS
(SELECT COLUMN_NAME FROM GT_COLUMNS_NAMES );

SELECT * FROM GT_COLUMNS_NAMES WHERE COLUMN_NAME = 'NO_RECONTRATABLE';
SELECT COLUMN_NAME FROM ALL_TAB_COLUMNS WHERE OWNER = 'XXLINK' AND COLUMN_NAME = 'NO_RECONTRATABLE';
  
SELECT count(*) from ( SELECT  column_name FROM ALL_TAB_COLUMNS WHERE OWNER = 'XXLINK');
SELECT count(*)  FROM ALL_TAB_COLUMNS WHERE OWNER = 'XXLINK';


select * from GT_TABLE_NAMES  inner join GT_COLUMNS_NAMES on GT_TABLE_NAMES.TBL_NAME_ID = GT_COLUMNS_NAMES.COLUMN_TBL_NAME_ID
WHERE TBL_NAME_ID = 25;

SELECT COLUMN_NAME FROM GT_COLUMNS_NAMES order by COLUMN_NAME;
SELECT * FROM ALL_TAB_COLUMNS WHERE OWNER = 'XXLINK' AND TABLE_NAME = 'TBL_CANDIDATO';



SELECT  tbl_columns.column_name
  FROM ALL_TAB_COLUMNS tbl_columns
    WHERE  tbl_columns.OWNER = 'XXLINK' AND tbl_columns. TABLE_NAME = 'TBL_CANDIDATO';
    
SELECT * 
FROM ALL_TAB_COLUMNS 
WHERE TABLE_NAME = 'TBL_CANDIDATO' ;

SELECT USER FROM DUAL;